// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import mermaid from "astro-mermaid";
import starlightSidebarTopics from "starlight-sidebar-topics";

// Each package gets its own topic — the sidebar swaps based on which
// package the reader is currently inside. Topic items default to
// `Overview` only for packages whose content isn't ported yet; once a
// package has a full Diátaxis tree the items array expands to the five
// canonical sections per the blueprint.

function pkgTopic({ label, slug, sections = [] }) {
  const items = [{ label: "Overview", link: `/v/latest/${slug}/` }];

  for (const section of sections) {
    items.push({
      label: section.label,
      collapsed: section.collapsed ?? false,
      items: [{ autogenerate: { directory: `v/latest/${slug}/${section.dir}` } }],
    });
  }

  return {
    label,
    link: `/v/latest/${slug}/`,
    items,
  };
}

// Diátaxis-style section list for "narrow" packages (Seal, Herald, FS,
// Context, etc.) per the blueprint.
const fullSections = [
  { label: "Getting Started", dir: "getting-started", collapsed: false },
  { label: "Essentials", dir: "essentials", collapsed: true },
  { label: "Guides", dir: "guides", collapsed: true },
  { label: "Recipes", dir: "recipes", collapsed: true },
  { label: "Reference", dir: "reference", collapsed: true },
];

// Laravel-style domain section list for "broad" packages (Core, Cascade,
// AI). Inspired by Laravel's `Getting Started / Architecture Concepts /
// The Basics / Digging Deeper / …` structure.
const coreSections = [
  { label: "Getting Started", dir: "getting-started", collapsed: false },
  { label: "Architecture Concepts", dir: "architecture-concepts", collapsed: true },
  { label: "The Basics", dir: "the-basics", collapsed: false },
  { label: "Digging Deeper", dir: "digging-deeper", collapsed: true },
  { label: "CLI", dir: "cli", collapsed: true },
  { label: "Testing", dir: "testing", collapsed: true },
  { label: "Recipes", dir: "recipes", collapsed: true },
];

const cascadeSections = [
  { label: "Getting Started", dir: "getting-started", collapsed: false },
  { label: "Architecture Concepts", dir: "architecture-concepts", collapsed: true },
  { label: "The Basics", dir: "the-basics", collapsed: false },
  { label: "Digging Deeper", dir: "digging-deeper", collapsed: true },
  { label: "CLI", dir: "cli", collapsed: true },
  { label: "Recipes", dir: "recipes", collapsed: true },
  { label: "Reference", dir: "reference", collapsed: true },
];

// AI uses Laravel-style sections (no CLI or testing — AI has no CLI of
// its own). Providers are appended as a subgroup separately in the
// topic config below. Best Practices and Recipes are both hand-placed as
// a pair near the end (before Reference): Best Practices is an
// autogenerated directory section (a flat list of pillar pages — every
// page under v/latest/ai/best-practices/ is picked up automatically),
// while Recipes is hand-curated (see aiRecipesGroup below) so its many
// pages can split into logical task-based subgroups instead of one long
// flat list. The splice that pairs them lives in the AI topic config.
const aiSections = [
  { label: "Getting Started", dir: "getting-started", collapsed: false },
  { label: "Architecture Concepts", dir: "architecture-concepts", collapsed: true },
  { label: "The Basics", dir: "the-basics", collapsed: false },
  { label: "Digging Deeper", dir: "digging-deeper", collapsed: true },
  { label: "Observability", dir: "observability", collapsed: true },
  { label: "Reference", dir: "reference", collapsed: true },
];

// Best Practices — opinionated, pillar-per-page guidance ("what should a
// senior dev do, and why"). Sits right before the Recipes group so the two
// task-oriented sections live together. Autogenerated from the directory so
// every page under v/latest/ai/best-practices/ is reachable automatically.
const aiBestPracticesGroup = {
  label: "Best Practices",
  collapsed: true,
  items: [{ autogenerate: { directory: "v/latest/ai/best-practices" } }],
};

// AI Recipes — hand-curated, grouped by task area. Each entry points to a
// real page under v/latest/ai/recipes/<file>/. Labels mirror each page's
// own sidebar label; order within a group is curated (easiest first).
function recipe(label, name) {
  return { label, slug: `v/latest/ai/recipes/${name}` };
}

const aiRecipesGroup = {
  label: "Recipes",
  collapsed: true,
  items: [
    {
      label: "Agents and Tools",
      collapsed: false,
      items: [
        recipe("Basic agent", "basic-agent"),
        recipe("Tool-calling agent", "tool-calling-agent"),
        recipe("Multi-tool research agent", "agent-multi-tool-research-agent"),
        recipe("Extract structured data", "agent-extract-structured-data"),
        recipe("Vision document extraction", "agent-vision-document-extraction"),
        recipe("Silent tools", "silent-tools"),
        recipe("Tools that emit UI artifacts", "agent-silent-tools-ui"),
        recipe("Streaming tool guard", "streaming-tool-guard"),
        recipe("RAG with cache similarity", "rag-with-cache-similarity"),
      ],
    },
    {
      label: "Workflows",
      collapsed: true,
      items: [
        recipe("Content pipeline", "workflow-content-pipeline"),
        recipe("Resumable import job", "workflow-resumable-import-job"),
        recipe("Retry and cancellation", "workflow-with-retry-cancel"),
      ],
    },
    {
      label: "Supervisors",
      collapsed: true,
      items: [
        recipe("Support triage supervisor", "supervisor-support-triage"),
        recipe("Classifier fast-path triage", "supervisor-classifier-fast-path"),
        recipe("Review-panel supervisor", "supervisor-review-panel"),
      ],
    },
    {
      label: "Orchestrator",
      collapsed: true,
      items: [
        recipe("Stateful support bot", "orchestrator-stateful-support-bot"),
        recipe("Production stores", "orchestrator-production-stores"),
        recipe("Orchestrator as a tool", "orchestrator-as-tool"),
      ],
    },
    {
      label: "Planner",
      collapsed: true,
      items: [
        recipe("Autonomous task runner", "planner-autonomous-task-runner"),
        recipe("Research with sub-agents", "planner-research-with-sub-agents"),
      ],
    },
    {
      label: "Memory",
      collapsed: true,
      items: [
        recipe("Assistant with memory", "memory-assistant-with-memory"),
        recipe("Semantic recall", "memory-semantic-recall"),
      ],
    },
    {
      label: "Cost and Resilience",
      collapsed: true,
      items: [
        recipe("Cost tracking", "cost-tracking"),
        recipe("Cost per tenant", "cost-aggregate-per-tenant"),
        recipe("Budgets and SLOs", "cost-budgets-and-slo"),
        recipe("Provider fallback", "cost-provider-fallback"),
      ],
    },
    {
      label: "DX and Testing",
      collapsed: true,
      items: [
        recipe("Batch-classify a dataset", "dx-batch-classify-dataset"),
        recipe("Eval in CI", "dx-eval-in-ci"),
        recipe("Self-consistency voting", "dx-self-consistency-voting"),
        recipe("Deterministic supervisor tests", "dx-deterministic-supervisor-tests"),
      ],
    },
    {
      label: "Observability",
      collapsed: true,
      items: [
        recipe("Wire Panoptic", "observability-wire-panoptic"),
        recipe("Export to OTel and Langfuse", "observability-export-otel-langfuse"),
        recipe("Trace cost dashboard", "observability-trace-cost-dashboard"),
      ],
    },
  ],
};

// Diátaxis variant for context (no recipes — the surface is too small
// for a clean recipe to survive the dedupe).
const contextSections = fullSections.filter((s) => s.dir !== "recipes");

// Cache uses a hand-curated learning-path sidebar (easy → advanced) instead
// of autogenerated Diátaxis sections. Page slugs are flattened to
// /v/latest/cache/<file>/ (see each page's `slug:` frontmatter), so groups
// can mix pages from any physical folder without moving files. Order here IS
// the order in the sidebar.
function cacheItem(label, name) {
  return { label, slug: `v/latest/cache/${name}` };
}

const cacheTopic = {
  label: "Cache",
  link: "/v/latest/cache/",
  items: [
    { label: "Overview", link: "/v/latest/cache/" },
    {
      label: "Getting Started",
      collapsed: false,
      items: [
        cacheItem("Introduction", "introduction"),
        cacheItem("Quick Start", "quick-start"),
        cacheItem("Configuration", "configurations"),
      ],
    },
    {
      label: "Everyday Caching",
      collapsed: false,
      items: [
        cacheItem("Cache Manager", "cache-manager"),
        cacheItem("Set Options", "set-options"),
        cacheItem("Tags", "tags"),
        cacheItem("Namespaces", "namespaces"),
        cacheItem("Best Practices", "best-practices"),
      ],
    },
    {
      label: "Caching Patterns",
      collapsed: true,
      items: [
        cacheItem("cached()", "cached"),
        cacheItem("Distributed Locks", "lock"),
        cacheItem("Stale-While-Revalidate", "swr"),
        cacheItem("Update & Merge", "update-merge"),
        cacheItem("Lists", "lists"),
        cacheItem("Atomic Operations", "atomic-operations"),
        cacheItem("Bulk Operations", "bulk-operations"),
        cacheItem("Stampede Prevention", "stampede-prevention"),
        cacheItem("Similarity Retrieval", "similarity"),
      ],
    },
    {
      label: "Recipes",
      collapsed: true,
      items: [
        cacheItem("Per-User / Multi-Tenant", "multi-tenant-cache"),
        cacheItem("Recent-Activity Feed", "recent-activity-feed"),
        cacheItem("Caching an External API", "cached-api"),
        cacheItem("Rate Limiting", "rate-limiting"),
        cacheItem("Distributed Job Guard", "job-guard"),
        cacheItem("Semantic LLM Cache", "semantic-llm-cache"),
      ],
    },
    {
      label: "Cache Drivers",
      collapsed: true,
      items: [
        cacheItem("Choosing a Driver", "choosing-a-driver"),
        cacheItem("Memory", "memory"),
        cacheItem("Memory Extended", "memory-extended"),
        cacheItem("LRU Memory", "lru-memory"),
        cacheItem("File", "file"),
        cacheItem("Redis", "redis"),
        cacheItem("Postgres", "pg"),
        cacheItem("Null", "null"),
        cacheItem("Make Your Own Driver", "make-your-own-cache-driver"),
      ],
    },
    {
      label: "Observability & Testing",
      collapsed: true,
      items: [
        cacheItem("Events", "events"),
        cacheItem("Metrics", "metrics"),
        cacheItem("Errors", "errors"),
        cacheItem("Testing", "testing"),
      ],
    },
    {
      label: "API Reference",
      collapsed: true,
      items: [
        cacheItem("Cache Driver Interface", "cache-driver-interface"),
        cacheItem("Base Cache Driver", "base-cache-driver"),
        cacheItem("Utilities", "utils"),
        cacheItem("Comparison", "comparison"),
      ],
    },
  ],
};

const topics = [
  // Foundation
  pkgTopic({ label: "Core", slug: "core", sections: coreSections }),
  pkgTopic({ label: "Create Warlock", slug: "create-warlock" }),
  pkgTopic({ label: "Seal", slug: "seal", sections: fullSections }),
  // Logger uses a custom 4-section structure (Getting Started · Channels ·
  // Advanced · API Reference) instead of the generic Diátaxis sections —
  // see domains/logger/plans for the full rationale.
  {
    label: "Logger",
    link: "/v/latest/logger/",
    items: [
      {
        label: "Getting Started",
        collapsed: false,
        items: [
          // Overview lives at the package root (logger/index.mdx) so external
          // links like /v/latest/logger/ keep working — surface it here as the
          // first Getting Started item instead of duplicating as a top-level
          // sidebar entry.
          { label: "Overview", link: "/v/latest/logger/" },
          { autogenerate: { directory: "v/latest/logger/getting-started" } },
        ],
      },
      {
        label: "Channels",
        collapsed: false,
        items: [{ autogenerate: { directory: "v/latest/logger/channels" } }],
      },
      {
        label: "Advanced",
        collapsed: true,
        items: [{ autogenerate: { directory: "v/latest/logger/advanced" } }],
      },
      {
        label: "Recipes",
        collapsed: true,
        items: [{ autogenerate: { directory: "v/latest/logger/recipes" } }],
      },
      {
        label: "API Reference",
        collapsed: true,
        items: [{ autogenerate: { directory: "v/latest/logger/reference" } }],
      },
    ],
  },
  pkgTopic({ label: "Context", slug: "context", sections: contextSections }),
  pkgTopic({ label: "File System", slug: "fs", sections: fullSections }),

  // Data
  pkgTopic({ label: "Cascade", slug: "cascade", sections: cascadeSections }),
  cacheTopic,

  // Lifecycle
  pkgTopic({ label: "Auth", slug: "auth", sections: fullSections }),
  pkgTopic({ label: "Access", slug: "access", sections: fullSections }),
  pkgTopic({ label: "Scheduler", slug: "scheduler", sections: fullSections }),
  pkgTopic({ label: "Herald", slug: "herald", sections: fullSections }),
  pkgTopic({ label: "Notifications", slug: "notifications", sections: fullSections }),

  // AI uses Laravel-style sections + a Providers subgroup with the 5
  // adapter pages nested in. Custom items array (not via pkgTopic) so we
  // can append Providers after the autogenerate sections.
  {
    label: "AI",
    link: "/v/latest/ai/",
    items: [
      { label: "Overview", link: "/v/latest/ai/" },
      // Getting Started → Architecture Concepts → The Basics → Digging
      // Deeper → Observability (autogenerated), then the Best Practices
      // group and the hand-curated Recipes group as a pair, then
      // Reference. Both are spliced in before Reference to preserve the
      // original section order.
      ...aiSections
        .map((s) => ({
          label: s.label,
          collapsed: s.collapsed,
          items: [{ autogenerate: { directory: `v/latest/ai/${s.dir}` } }],
        }))
        .flatMap((section) =>
          section.label === "Reference"
            ? [aiBestPracticesGroup, aiRecipesGroup, section]
            : [section],
        ),
      {
        label: "Providers",
        collapsed: true,
        items: [
          { label: "OpenAI", slug: "v/latest/ai/providers/openai" },
          { label: "Anthropic", slug: "v/latest/ai/providers/anthropic" },
          { label: "Bedrock", slug: "v/latest/ai/providers/bedrock" },
          { label: "Google", slug: "v/latest/ai/providers/google" },
          { label: "Ollama", slug: "v/latest/ai/providers/ollama" },
          { label: "Mistral", slug: "v/latest/ai/providers/mistral" },
          { label: "Groq", slug: "v/latest/ai/providers/groq" },
          { label: "DeepSeek", slug: "v/latest/ai/providers/deepseek" },
          { label: "xAI (Grok)", slug: "v/latest/ai/providers/xai" },
        ],
      },
    ],
  },
];

// Global pages that don't belong to any package topic (landing, packages
// grid, skills explainer, 404). They render with no sidebar — fine for
// landing-style pages.
const excludedFromTopics = ["/", "/index", "/packages", "/skills", "/changelog", "/404"];

// https://astro.build/config
export default defineConfig({
  site: "https://warlock.js.org",
  integrations: [
    // mermaid must run BEFORE starlight per astro-mermaid's docs.
    // themeVariables are layered on top of autoTheme's default/dark base
    // — pick values that look right under our warlock yellow palette.
    mermaid({
      autoTheme: true,
      mermaidConfig: {
        themeVariables: {
          // Node fills + borders
          primaryColor: "#161b29",
          primaryBorderColor: "#f5b800",
          primaryTextColor: "#e2e8f0",
          secondaryColor: "#1c2030",
          tertiaryColor: "#1c2030",
          // Edges + labels
          lineColor: "#94a3b8",
          edgeLabelBackground: "#0f1422",
          labelBackground: "#0f1422",
          // Background + main fills
          background: "transparent",
          mainBkg: "#161b29",
          // Cluster (subgraph) chrome
          clusterBkg: "rgba(245, 184, 0, 0.04)",
          clusterBorder: "#3a4256",
          // Notes
          noteBkgColor: "#1c2030",
          noteTextColor: "#e2e8f0",
          noteBorderColor: "#f5b800",
          // Activation bars (sequence)
          activationBkgColor: "#f5b800",
          activationBorderColor: "#f5b800",
          // Actor (sequence)
          actorBkg: "#161b29",
          actorBorder: "#f5b800",
          actorTextColor: "#e2e8f0",
          actorLineColor: "#3a4256",
          // Sequence message colors
          signalColor: "#e2e8f0",
          signalTextColor: "#e2e8f0",
          // State diagram
          fillType0: "#161b29",
          fillType1: "#1c2030",
          fillType2: "#252b3d",
        },
        flowchart: {
          curve: "basis",
          padding: 14,
          htmlLabels: true,
        },
        sequence: {
          actorMargin: 50,
          messageMargin: 40,
          mirrorActors: false,
        },
      },
    }),
    starlight({
      title: "Warlock.js",
      description:
        "AI-native TypeScript framework for backend, real-time, and AI operations.",
      head: [
        {
          tag: "meta",
          attrs: {
            name: "google-site-verification",
            content: "ARcACUyhaNj7uvsLp5qhjGhzWvOQMqX9ZGxS8wpHT0I",
          },
        },
        // Open Graph / Twitter social-card image (link previews in
        // WhatsApp, Slack, Telegram, X, …). og:title/description/url are
        // emitted per-page by Starlight; only the image needs adding.
        { tag: "meta", attrs: { property: "og:type", content: "website" } },
        {
          tag: "meta",
          attrs: { property: "og:image", content: "https://warlock.js.org/og.png" },
        },
        { tag: "meta", attrs: { property: "og:image:width", content: "1200" } },
        { tag: "meta", attrs: { property: "og:image:height", content: "630" } },
        {
          tag: "meta",
          attrs: {
            property: "og:image:alt",
            content: "Warlock.js — AI-native TypeScript framework",
          },
        },
        { tag: "meta", attrs: { name: "twitter:card", content: "summary_large_image" } },
        {
          tag: "meta",
          attrs: { name: "twitter:image", content: "https://warlock.js.org/og.png" },
        },
      ],
      components: {
        // Full chrome replacement — header, sidebar, footer all custom.
        Header: "./src/components/Header.astro",
        Sidebar: "./src/components/Sidebar.astro",
        Footer: "./src/components/Footer.astro",
      },
      customCss: ["./src/styles/global.css"],
      logo: {
        src: "./src/assets/logo.png",
        alt: "Warlock.js",
        replacesTitle: false,
      },
      favicon: "/favicon.png",
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/warlockjs/core",
        },
      ],
      editLink: {
        baseUrl: "https://github.com/warlockjs/core/edit/main/@warlock.js/docs/",
      },
      lastUpdated: true,
      pagination: true,
      plugins: [starlightSidebarTopics(topics, { exclude: excludedFromTopics })],
    }),
  ],
});
